### ISSUE TITLE
"Bad git executable" error on Windows command prompt

### ISSUE THREAD

**Issue by dimi309** [bincrafters/conan-readme-generator#1]
Great tool! I've just used it for the first time. I really like how it also detects and adds a package's options in the README.

I have tried it on windows and it works fine when run inside Git Bash. If I run it from a windows command prompt though (always under my python virtualenv), I get the error below, even if I have git in the path and in the GIT_PYTHON_GIT_EXECUTABLE variable. It's not a big problem and I suppose it has more to do with the git wrapper, but anyway I thought to let you know.

```
(vconan) C:\Users\user\Source\conan-opus>conan-readme-generator bincrafters/stable
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\user\Source\vconan\Scripts\conan-readme-generator.exe\__main__.py", line 5, in <module>
  File "c:\users\user\source\vconan\lib\site-packages\conan_readme_generator\main.py", line 8, in <module>
    from conan_readme_generator.readme_templater import BincraftersTemplater
  File "c:\users\user\source\vconan\lib\site-packages\conan_readme_generator\readme_templater.py", line 7, in <module>
    from git import Repo
  File "c:\users\user\source\vconan\lib\site-packages\git\__init__.py", line 82, in <module>
    refresh()
  File "c:\users\user\source\vconan\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "c:\users\user\source\vconan\lib\site-packages\git\cmd.py", line 293, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```

**Comment by sigmoidal** [comment]
I am just loading GitPython. I think we shouldn't configure the git environment in the tool, but if you know how, we can do it.

I cannot replicate it, but I found this: https://github.com/gitpython-developers/GitPython/issues/26

Have a look and if there is something we can do to fix it let me know. I'd be happy to clean it up.

**Comment by dimi309** [comment]
You know what, I've just managed to make it work now using the GIT_PYTHON_GIT_EXECUTABLE variable. My mistake was setting it using double quotes like this: `SET GIT_PYTHON_GIT_EXECUTABLE="C:\Program Files\Git\bin\git.exe"`, which doesn't work. This works on the other hand: `SET GIT_PYTHON_GIT_EXECUTABLE=C:\Program Files\Git\bin\git.exe`
Thanks in any case!
